### ISSUE TITLE
Feature Request: Changing Font in Editor

### ISSUE THREAD

**Issue by Blockguy24** [litdev1/SB-IDE#11]
Sometimes I find that I want to change the text editor font to something else, but when I look in the options, there is no way to change the font for the text editor. Would this be possible to add?

**Comment by litdev1** [comment]
Hi, I added this.
To get new version do Advanced->Update
To modify the font family do Advanced->Options

**Comment by Blockguy24** [comment]
Thanks, this works very nicely.
