### ISSUE TITLE
Bugs (Intellisense, Syntax Highlighting and Auto Indentation)

### ISSUE THREAD

**Issue by Blockguy24** [litdev1/SB-IDE#2]
# Variables and labels starting with keywords
When using certain variable names that start with a reserved keyword such as `order`, the first two letters (`or`) gets highlighted, even though `order` isn't a keyword.
This bug isn't just a cosmetic problem though, they also don't appear in Intellisense
![image](https://user-images.githubusercontent.com/21016331/74507668-35190980-4f51-11ea-9718-0a38af03aac4.png)
![image](https://user-images.githubusercontent.com/21016331/74507864-bf616d80-4f51-11ea-8e04-cab34a18f834.png)

# Intellisense appearing in comments
Not sure if this is intentional or not, but this is mostly just a cosmetic issue:
![image](https://user-images.githubusercontent.com/21016331/74507988-10716180-4f52-11ea-8cf1-aaa79a1afc74.png)

# `ElseIf` and `Else` getting auto-indented incorrectly
When using `ElseIf` or `Else` inside an `If` block, pressing Enter after it should result in it un-indenting automatically, but it just stays indented. Pressing Enter after a manually un-indented statement results in it re-indenting (animated gif):
![2020-02-14_18-37-47](https://user-images.githubusercontent.com/21016331/74511271-bf656b80-4f59-11ea-9f83-73e7f930b67f.gif)
Pressing the "Format" button works as intended, and is a somewhat suitable, if not annoying workaround.

# Conclusion
Although buggy, this is a great IDE for small basic, with tons of features not found in the official small basic IDE.

**Comment by litdev1** [comment]
Hi,
Thanks for taking the time to mention these bugs.
SB-Prime is just a hobby project when MS development of SB seemed to stall a few years ago.
The indentation was a simple typo and the AND OR was a mix up in regex for operator highlighting
Hopefully fixed these issues - just hit the Advanced|Update button in the interface to upgrade.

**Comment by Blockguy24** [comment]
It seems to all be working now, thanks for such a quick update!
