### ISSUE TITLE
IDE windows should have minimum window size

### ISSUE THREAD

**Issue by Blockguy24** [litdev1/SB-IDE#3]
One thing that I've noticed when dragging around SB-Prime's windows is that sometimes they do this:
![image](https://user-images.githubusercontent.com/21016331/74644615-a6172600-51ca-11ea-95b0-61af61fd1001.png)
This can make it difficult to "grab" onto the window, or resize it for that matter.

Not sure how easy/difficult this is to set up, but setting minimum window sizes for all windows throughout SB-Prime should fix this.

**Comment by litdev1** [comment]
Hi,
Had a go at minimum window sizes, 600x400 for the main window and 100x100 for all others that can resize.
Advanced|Update to get this.

**Comment by Blockguy24** [comment]
I think that the minimum width of the other windows should be 220 pixels. The height of 100 seems to be fine.

Current (width capped at 136 due to window buttons):
![image](https://user-images.githubusercontent.com/21016331/74713200-2fd2fc00-527c-11ea-89f7-5e07a1b67b47.png)

Proposed (width of 220):
![image](https://user-images.githubusercontent.com/21016331/74713250-57c25f80-527c-11ea-9cd4-c31bc004cae4.png)

**Comment by litdev1** [comment]
Hi,
I updated as you suggest.

However, minimum window size is not really there to be a usable window, rather just enough to see what it is and get the resize corners to resize it to a usable size to work in.  It was the completely shrunk window that I was trying to fix.  

Compare with minimum size for File Explorer - typical for Windows.

![Untitled](https://user-images.githubusercontent.com/13494667/74770324-eedee580-5283-11ea-9f4f-39ea26902bed.png)

**Comment by Blockguy24** [comment]
Yeah I see what you mean, closing this issue.
