### ISSUE TITLE
SB-Prime IDE translation

### ISSUE THREAD

**Issue by triksterr** [litdev1/SB-IDE#6]
Hello!

Now I have tested your "mechanical" Russian translation. I was find so many mistakes in it.
I can edit it, but I need some more information.  Can you make SB_Prime.Properties.Strings.ru.resx file with original English phrases in Comment field for each phrase?

**Comment by litdev1** [comment]
OK, if the machine translation is poor (worse than no translation) then I will only include translations that have been verified by a native speaker.

The resx files (original and translated) are auto created so comments would also be translated.

But I can give excel with both translations and then paste the corrected ru back into the ru.resx.  It does mean that any new stuff added to the IDE willl not get a translation until added manually, but that shouldn't be often or a very much.

So here is the current excel.

[localisation.xlsx](https://github.com/litdev1/SB-IDE/files/4355853/localisation.xlsx)

**Comment by triksterr** [comment]
Ок. Thanks.
Now I will read and correct translations. :)
What about your e-mail for future direct connections?
My email is triksterr@gmail.com.

**Comment by triksterr** [comment]
And... how can I convert localisation.xlsx to SB_Prime.Properties.Strings.ru.resx for chesking directly? :)

Because I need to see the words in the IDE interface directly for understanding of correct translation. I am not sure about positions of the text for understanding what this text means.

**Comment by litdev1** [comment]
I can do that easily in VS.  I checked in the current machine translation version.

**Comment by triksterr** [comment]
Ok. I did it. :)
https://stackoverflow.com/questions/11133549/how-convert-xls-to-resx

**Comment by litdev1** [comment]
It is a simple copy and paste for me in Visual Studio - a few seconds work.  All I need is the excel with good translations.

![Untitled](https://user-images.githubusercontent.com/13494667/77190526-53829f80-6ad1-11ea-92d7-d91b9068edff.png)

**Comment by triksterr** [comment]
Thanks! :)
It's ok already.

**Comment by litdev1** [comment]
If you have VS and the SB-Prime project then you can test, just copy the excel columns into the ru.resx or give me the converted excel and I will do it and publish the compiled versin for test.

**Comment by triksterr** [comment]
Ок. I'm editing the .resx file in VS now.

**Comment by triksterr** [comment]
Hello!

I did full Russian translation of IDE completely.
It was checked by 4 Russian people now.
[Strings.ru.zip](https://github.com/litdev1/SB-IDE/files/4387684/Strings.ru.zip)

**Comment by litdev1** [comment]
Thanks - received - this is great.  I will hold off advertising this new feature and asking if others want to provide other language translations till we sort out the other bugs you have spotted.

**Comment by triksterr** [comment]
OK.
I have some remarks.
The part of the interface strings left untranslated - they are not in the resource file.
- Extension Manager
- Graduate - the part of the text in the modal window
- Decompile - the part of the text in the modal window
- Output, Errors and Warnings - message sources keys
- Colors - names of interface elements
- Statusline - all
- Flow Chart - "START" and "END"

You can insert these texts in xlsx table (without Russian translation) and send it to me.

Also, I would like to edit of the Spanish translation. Can You send me Spanish resx or xlsx file?

**Comment by litdev1** [comment]
Yep - extension manager is a totally separate dll so would have to have its own - maybe leave that just now.
Colors - I did keep since they are the MS color names used in SB code
Will check ou the others - bits may auto detection of strings didn't catch - Thanks

**Comment by litdev1** [comment]
Thanks - will also send ru and es translations when ready/merged with the remaining strings

**Comment by triksterr** [comment]
> Colors - I did keep since they are the MS color names used in SB code

I’m not talking about the names of the colors, but I’m talking about the names of the IDE elements whose colors can be changed in RGB. :)

**Comment by litdev1** [comment]
"I’m not talking about the names of the colors, but I’m talking about the names of the IDE elements whose colors can be changed in RGB. :)"

Sorry, still not totally clear what this is - on insert color tool?

**Comment by triksterr** [comment]
This is not insert color tool! :)
It is the color settings of the IDE editor (Advanced - IDE colors).

**Comment by triksterr** [comment]
This is the last Russian translation:
[localisation.xlsx](https://github.com/litdev1/SB-IDE/files/4397125/localisation.xlsx)

What about any other strings?

**Comment by litdev1** [comment]
Ah I see - yes I didn't notice these because the names are actually used internally as the variable ids, not string literals - this was so its easy to add more and store in the settings etc.  A more extendive coding change would be needed to do these - will have a look.

**Comment by litdev1** [comment]
I have updated the code to handle the IDE color string labels and checked into GitHub String124 to String167 in the resx for ru and es.

**Comment by triksterr** [comment]
Ок. I think only the statusline was left. Isn't it? :)

**Comment by litdev1** [comment]
Yes, hopefully that is it - String168 to String 177, checked in the resx for statusline for ru and es.

**Comment by triksterr** [comment]
It's done.
[Strings.ru.zip](https://github.com/litdev1/SB-IDE/files/4399604/Strings.ru.zip)

**Comment by litdev1** [comment]
Thanks,
Advanced->Update should work to the latest version

**Comment by triksterr** [comment]
I know.
Now I will make Espanol translation.

And... I think You need make some more translations: Chinese, Hindi, Arabic, Bengali, Portuguese, French and possible Japanese and Italian.
