### ISSUE TITLE
Comment highlighting

### ISSUE THREAD

**Issue by triksterr** [litdev1/SB-IDE#8]
In the editor window I have find one mistake: if I turn a line of code into a comment manually and then use Context menu (right mouse) -> "Un-Comment line", I see green and italic code line without leading "\'". The reverse sequence is the same.

**Comment by triksterr** [comment]
By the way (about shortcuts), in the new SB the keyboard shortcut "Ctrl +?" - comments / uncomments a line of code.

**Comment by litdev1** [comment]
Thanks - will look at these

**Comment by litdev1** [comment]
I cannot reproduce or do not follow exactly how to reproduce this issue.

I did add "Ctrl +?" hotkey.

**Comment by triksterr** [comment]
> I cannot reproduce or do not follow exactly how to reproduce this issue.

I just checked version 1.1.7 - there I can not reproduce this error.
Probably it was present only in version 1.1.6.
I hope it is fixed.

> I did add "Ctrl +?" hotkey.

It is OK! Thanks! :)

**Comment by triksterr** [comment]
I caught it!

I enter any string: "kljkljkj".
Then I execute the context menu command "Comment lines".
I see green italic font in the string.
Then I delete the first comment symbol in string manually.
I see: green italic font in the string is not changes.
IDE version 1.1.7

![string](https://user-images.githubusercontent.com/48825903/77822881-b1ce0480-7107-11ea-859c-76cac69b6c01.PNG)

**Comment by litdev1** [comment]
Yeh, the lexer only updates every so often then when the line changes or a character is added based on event that it receives.  Looks like this happens when there is only one line and a quirk of the lexer (Scintilla) and not really worth the effort to try to treat as a special case.

**Comment by triksterr** [comment]
![lll](https://user-images.githubusercontent.com/48825903/77857385-b7117900-7205-11ea-8ed4-fee2f6a6016b.PNG)
There are multi strings...

**Comment by litdev1** [comment]
mmm - I can only seem to reproduce on a line without CR (return new-line), which is always the last line and maybe considered a line that hasn't been finished yet?

**Comment by triksterr** [comment]
Probably the problem is that the lexer "does not know" how to fully work with Russian (and probably all another languages) letters. The code in original MS SB IDE can be written in any language.

Now I am completing the educational extension library in Russian - for Russian children. This extension library works in MS SB IDE. I have not tested it in SB-Prime yet.

**Comment by triksterr** [comment]
I think You need to add this secuence into all Regex rules: "а-яА-ЯёЁ".
And maybe to do something else... :)

**Comment by litdev1** [comment]
This is tricky again since I can't reproduce anything that is a significant issue - as soon as any line is ended (e.g. return) it updates comments correctly for me.

Russian letters have nothing to do with what comes after a ' for a comment.

All keywords etc have no russian characters, only possibilities are (after comments, inside quotes or variable names) - none of which are affected by the regex syntaxing.

So I am missing something and therefore have no place to start 'fixing'.

Since you have got the code, can see the issue and think you have a solution, have a go.
